[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "hmetrics"
version = "0.1.0"
dependencies = ["requests", "yfinance"]

[project.scripts]
hmetrics = "hmetrics.__main__:main"
