[build-system]
requires = ["setuptools>= 69.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "hmetrics"
version = "0.1.0"
dependencies = ["requests", "yfinance"]

[project.scripts]
hmetrics = "hmetrics.__main__:main"
