[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "hmetrics"
version = "0.1.0"
dependencies = ["hcommon @ {root:parent:uri}/hcommon", "requests"]

[project.scripts]
hmetrics = "hmetrics.__main__:main"

[tool.hatch.metadata]
allow-direct-references = true
