[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "htreas"
version = "0.1.0"
dependencies = ["hcommon @ {root:parent:uri}/hcommon"]

[project.scripts]
htreas = "htreas.__main__:main"

[tool.hatch.metadata]
allow-direct-references = true
