[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "hstocks"
version = "0.1.0"
dependencies = ["yfinance"]

[project.scripts]
hstocks = "hstocks.__main__:main"
